# For C/C++ compilation
image: gcc

stages:
    - setup
    - build
    - test

before script:
    # Install cmake (build dependencies
    stage: setup
    script: 
        - apt-get update --yes
        - apt-get -y install cmake
    
smooth:
    # Build the application
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make

smooth_tests:
    # Run the unit smooth_tests
    stage: test
    script: make test