# For C/C++ compilation
image: gcc

stages:
    - buildtest
    
smooth:
    # Build the application and run the test
    stage: buildtest
    script:
        - apt-get update --yes
        - apt-get -y install cmake
        - git submodule init
        - git submodule update
        - mkdir build
        - cd build
        - cmake ..
        - make
        - make test