# For C/C++ compilation
image: gcc

before script:
    # Install cmake (build dependencies
    script:
        - apt-get update && apt-get -y install cmake
    
smooth:
    # Build the application
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - make test